import turtle

turtle.showturtle()
turtle.left(45)
turtle.forward(100)
turtle.left(90)
turtle.forward(100)
turtle.left(90)
turtle.forward(100)
turtle.left(90)
turtle.forward(100)
turtle.left(90)
turtle.penup()
turtle.color("red")
turtle.goto(-100, -100)
turtle.pendown()
turtle.circle(50)
turtle.hideturtle()
turtle.done()
